-- 로컬 Supabase(supabase start) 전용 부트스트랩 — Production에 적용하지 않는다.
--
-- local_jobs 등 초기 테이블은 저장소 migrations에 CREATE 문이 없어서(대시보드에서
-- 먼저 만들어짐) 빈 로컬 DB에 migrations만 돌리면 재현이 안 된다. 이 파일은
-- 20260927090000_job_alerts.sql 검증에 필요한 부분만 2026-09-27 Production
-- information_schema/pg_policies/pg_get_functiondef를 read-only로 조회한 결과로
-- 재구성했다(geog geography 컬럼은 postgis 의존이라 제외, 나머지 컬럼·제약·RLS·
-- 가입 트리거는 동일).
--
-- 사용: 로컬 supabase 프로젝트의 migrations에 이 파일을 가장 앞 순서로, 그 뒤에
-- supabase/migrations/20260927090000_job_alerts.sql을 넣고 `supabase start`.
-- 검증 스크립트: supabase/tests/job_alerts_rls_test.sql

create table public.account_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('seeker', 'employer')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.account_statuses (
  user_id uuid primary key references auth.users(id) on delete cascade,
  status text not null default 'active' check (status in ('active', 'suspended')),
  reason text,
  suspended_at timestamptz,
  suspended_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.local_jobs (
  id bigint generated by default as identity primary key,
  title text not null, company text not null, category text default 'other', salary text, location text,
  hours text, employer_phone text, application_deadline date, urgent boolean default false, description text,
  posted_at date default current_date, lat numeric, lng numeric, active boolean default true,
  created_at timestamptz default now(), image_url text, source text, work_period text, work_days text,
  education text, preference text, num_hires text, company_verified boolean default false,
  company_founded_year integer, hire_count integer, images jsonb, employer_id uuid references auth.users(id),
  origin text not null default 'legacy' check (origin in ('crawler', 'employer', 'admin', 'legacy')),
  admin_hidden boolean not null default false, source_url text, crawler_version text,
  last_verified_at timestamptz, publish_gate_reason text, recruitment_regions text[], subcategory text,
  job_duration text, gender_requirement text, age_requirement text, labor_contract_pledge boolean,
  social_insurance_pledge boolean, guest_manage_token text,
  salary_min integer, salary_max integer,
  salary_currency text check (salary_currency is null or salary_currency in ('VND', 'USD')),
  salary_period text check (salary_period is null or salary_period in ('hour', 'day', 'month', 'other')),
  salary_negotiable boolean,
  shift_type text check (shift_type is null or shift_type in ('day', 'night', 'rotating', 'other')),
  work_start_time time, work_end_time time,
  check (salary_min is null or salary_max is null or salary_min <= salary_max)
);

create table public.job_work_locations (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.local_jobs(id) on delete cascade,
  raw_address text not null, normalized_address text, country text not null default 'VN',
  province text, district text, ward text, lat double precision, lng double precision,
  geocode_status text not null default 'pending' check (geocode_status in ('pending', 'success', 'failed', 'manual')),
  geocode_source text, location_verified boolean not null default false, sort_order integer not null default 0,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  address_accuracy text check (address_accuracy in ('exact_text', 'region_only', 'undetermined')),
  coordinate_accuracy text check (coordinate_accuracy in ('exact', 'ward', 'region', 'unresolved')),
  address_evidence text, matched_recruitment_regions text[], resolved_province text, resolved_wards text[],
  unique (job_id, normalized_address)
);

create or replace function public.is_admin() returns boolean language sql stable
set search_path to 'pg_catalog', 'public' as $$
  select auth.uid() is not null and coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin';
$$;

create or replace function public.is_account_active(user_id uuid) returns boolean language sql stable
security definer set search_path to 'pg_catalog', 'public' as $$
  select user_id is not null and exists (
    select 1 from public.account_statuses s where s.user_id = $1 and s.status = 'active');
$$;

create or replace function public.local_job_is_visible(p_active boolean, p_admin_hidden boolean, p_employer_id uuid)
returns boolean language sql stable set search_path to 'public' as $$
  select (p_active is true and p_admin_hidden is false)
    or (auth.uid() is not null and p_employer_id is not null and p_employer_id = auth.uid())
    or public.is_admin();
$$;

create or replace function public.handle_new_auth_user_role() returns trigger language plpgsql
security definer set search_path to 'public' as $$
declare requested_role text;
begin
  requested_role := coalesce(new.raw_user_meta_data ->> 'role', 'seeker');
  if requested_role not in ('seeker', 'employer') then requested_role := 'seeker'; end if;
  insert into public.account_roles (user_id, role) values (new.id, requested_role) on conflict (user_id) do nothing;
  return new;
end;
$$;

create or replace function public.handle_new_auth_user_status() returns trigger language plpgsql
security definer set search_path to 'pg_catalog', 'public' as $$
begin
  insert into public.account_statuses (user_id, status) values (new.id, 'active') on conflict (user_id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_auth_user_role();
create trigger on_auth_user_created_status after insert on auth.users
  for each row execute function public.handle_new_auth_user_status();

alter table public.account_roles enable row level security;
alter table public.account_statuses enable row level security;
alter table public.local_jobs enable row level security;
alter table public.job_work_locations enable row level security;

create policy account_roles_select_own on public.account_roles for select to authenticated
  using (user_id = auth.uid() or coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin');
create policy account_statuses_select_own_or_admin on public.account_statuses for select to authenticated
  using (user_id = auth.uid() or public.is_admin());
create policy local_jobs_public_select on public.local_jobs for select to anon, authenticated
  using (public.local_job_is_visible(active, admin_hidden, employer_id));
create policy job_work_locations_public_select on public.job_work_locations for select to anon, authenticated
  using (exists (select 1 from public.local_jobs l where l.id = job_work_locations.job_id
                 and public.local_job_is_visible(l.active, l.admin_hidden, l.employer_id)));

revoke all privileges on table public.account_roles, public.account_statuses, public.local_jobs, public.job_work_locations from anon, authenticated;
grant select on table public.account_roles, public.account_statuses to authenticated;
grant select on table public.local_jobs, public.job_work_locations to anon, authenticated;
